### ISSUE TITLE
Unable to generate unit test via Chatunitest IDEA plugin 

### ISSUE THREAD

**Issue by Pallav-552** [ZJU-ACES-ISE/chatunitest_plugin_idea#3] opened 2023-11-10 09:20 UTC
On selecting "Chatunitest Generate Tests" for a method , I only see below notification from chatunitest but don't see the testoutput folder getting created under my project directory. 
![Selection_094](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/9f60e79f-460f-4bd5-b552-a222952ab0b5)

And even don't find any logs or info under my  tmpoutput folder.

**Comment by NCCurry30** [comment] 2023-11-10 10:13
Please check if your project has been compiled, or you can select the option to compile with IntelliJ IDEA compiler as below shows
![image](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/80865961/f7c8cdbf-e66c-4099-bacd-c566cc521f0b)
![image](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/80865961/4be11b1e-8c21-4c29-a148-a7a43e28f031)
Moreover, you need to choose "parse the project" for the first time with the project to ensure that the parsing results are consistent with the project
![image](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/80865961/0c4c4f29-1840-4fce-b211-d43d08b361cc)

**Comment by Pallav-552** [comment] 2023-11-10 10:32
Project is compiled manually and it was success. But I am getting notification on "Parse the project" by ChatUnitest.
[ChatUniTest] Parsing class info
[ChatUniTest] Project parse failed

And don't see any error details.

**Comment by NCCurry30** [comment] 2023-11-10 10:49
Could you please provide the structure of your project？

**Comment by Pallav-552** [comment] 2023-11-10 11:23
![Selection_095](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/0f8e8764-c720-4f7e-acd7-42f7ef031e9a)


Project structure is something like above which is following parent-child project structure . Actual code is inside abc-core.
`<dependency>
            <groupId>io.github.ZJU-ACES-ISE</groupId>
            <artifactId>chatunitest-starter</artifactId>
            <version>1.0.0</version>
            <type>pom</type>
        </dependency>`
 Chatunitest dependency is added in pom.xml of abc-core 

Thanks.

**Comment by NCCurry30** [comment] 2023-11-10 12:29
Thanks for the question，this problem is caused by complex multi-modules，we have added support for multi-module projects in version 3.1 of the plugin, you can find the latest version of the plugin at the following [ChatUniTest IDEA plugin](https://plugins.jetbrains.com/plugin/22522-chatunitest/edit/versions) or Jetbrain marketplace.

**Comment by Pallav-552** [comment] 2023-11-10 12:53
I think I have added the latest plugin only but I will reconfirm and update . 
Pom.xml dependency should be same ryt what is given by me ?

**Comment by Pallav-552** [comment] 2023-11-10 16:01
I have updated the IDEA plugin to 3.1 and now the Parsing the project is completing but Test case generation is not completing but no error too. 
![Selection_098](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/8ce981cd-84bb-4333-9c34-e201460704d8)

Post the activity I can see /tmp folder getting created with class-map.json but testoutput folder is not created. I only see below notification in IDE.
![Selection_097](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/f71e933d-4a7a-4155-8456-794fc9a3a203)

**Comment by NCCurry30** [comment] 2023-11-11 02:34
I think there may be some problems with the parsing result. Can you check the parsing result of the "addToExecutionLog" method in `tmp/class-info` folder to find whether the result is correct

**Comment by Pallav-552** [comment] 2023-11-27 09:05
So there are 2 issues which I have observed. : 
 1) There are multiple java files for which there is no details in /tmp/class-info due to which the generation of testcases struck with above screenshot in my last comment.
2) For those java clases for which mapping in /tmp/classs-info is present , 
           a) Test generation failed due to all rounds get exhausted in fixing the tests but still there are errors in generated tests.
           b)  There are some scenarios where I have got below notifications.
![Selection_163](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/f4c71531-b9de-4075-afc0-fa31d431cc08)

But till I am not seeing test files generated under /project/chatunitest/ directory .

**Comment by coder-chenzhi** [comment] 2023-11-30 00:52
@NCCurry30

**Comment by NCCurry30** [comment] 2023-11-30 07:43
Sorry, it seems that there are still some problems with the parsing of the multi-module project, and it is expected that the improvement of this problem will be fixed next week.

**Closed as completed** 2024-02-22 14:52 UTC
